server:
  port: ${PORT:7656}
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Registros
    username: postgres
    password: 123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop  # Esto permite que las tablas se creen y actualicen según las entidades
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
