server:
  port: ${PORT:8080}
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      schema-locations: classpath:schemas/schema-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-console
